# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ebdc68a0efec4403c2a24d9cea997a00e8abac73fa0b7edcd90013cb341ef0046d19e4d6a09e5c6082720476ab6aa33962c2eb6df1b6fb90a9fb1a62cbf3bbe

test:
  secret_key_base: 14488f4099b77f1aa835bf1df82bed9e023b39baff772b72c8d68b4ca56dcdb97268d90b723e0b48a122b5e985246226e579670377820b6ff490aa3a7d7cc024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
